### ISSUE TITLE
driverless driver

### ISSUE THREAD

**Issue by anotherfinemess84** [traplol/c-test#1]
Hello i wonder if you have contact details?  Thankyou

**Comment by anotherfinemess84** [comment]
Hi, are you available to talk?  Thanks

**Comment by traplol** [comment]
You can message me here.

**Comment by anotherfinemess84** [comment]
Yeh im just wondering if you do any freelance work.  I have a kernel driver
which protects a DLL, designed for working with a game.  So I am interested
in areas concerning PsProtection / Mitigation policies / VAD Hiding / CSRSS
/ Manual Mapping.

Thanks

**Comment by traplol** [comment]
Sure you can send me an email at ee35e7c782791419f29316f183d5d6@gmail.com
